### ISSUE TITLE
Proposal: Optional NLP Service Backchanneling

### ISSUE THREAD

**Issue by mr-martian** [gucorpling/midas-loop#3]
I think it would be useful if, in addition to requests to `/` containing data to be analyzed, external services could accept requests at some other endpoint containing which option the user selected as gold.

My specific usecase is that I want to write a service for running Apertium morphological analyzers (providing tokenization, POS tags, and FEATS). If the analysis came from a guesser rather than a dictionary entry, then knowing that the user selected that option would prompt the service to add an entry to the dictionary.

Admittedly, this can be done by later doing a scan of the corpus and comparing the gold annotations with the predictions. On the other hand, there are other situations in which this might be useful, such as if someone had a service for NER/coreference and the user marked a span as a new entity, this would allow the service to start including it as an option immediately (probably desirable since it's likely to show up in succeeding trees).

**Comment by mr-martian** [comment]
I just realized that when the user makes a change, the sentence gets sent back to the service for reparsing and all the data I want is in that later request and I just have to keep track of what I'm looking for a little differently.

**Comment by lgessler** [comment]
Glad your problem appears to be handled by the existing infra! Please don't hesitate to be in touch with further thoughts or enhancements :)
